services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    volumes:
      # Persistent data volumes
      - vectordb_data:/app/data

volumes:
  vectordb_data:
    name: vectordb_data
    driver: local
